//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisitorManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginView
    {
        public int Id { get; set; }
        public Nullable<int> PackageOrAdminId { get; set; }
        public string SName { get; set; }
        public string UserName { get; set; }
        public string UserId { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public Nullable<System.Guid> AuthCode { get; set; }
        public string Mobile2 { get; set; }
        public string UserType { get; set; }
    }
}
