//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisitorManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_country
    {
        public int Id { get; set; }
        public Nullable<int> country_id { get; set; }
        public string name { get; set; }
        public string iso_code_2 { get; set; }
        public string iso_code_3 { get; set; }
        public string address_format { get; set; }
        public string postcode_required { get; set; }
        public string status { get; set; }
    }
}
