//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisitorManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Payment
    {
        public int Id { get; set; }
        public int AdminId { get; set; }
        public string AdminAppId { get; set; }
        public string PaymentId { get; set; }
        public string Guid { get; set; }
        public string Token { get; set; }
        public string PayerID { get; set; }
        public System.DateTime Date { get; set; }
        public string Amount { get; set; }
    
        public virtual tbl_Administrator tbl_Administrator { get; set; }
    }
}
